version: '3'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    restart: unless-stopped
# volumes:
#   mediamtx.yml: